---
title: "DESCRIPTIVE ANALYSIS : Census Vs Survey"

output:
  html_document:
    df_print: paged
    geometry: "a4paper, margin=2cm,2cm,2cm,2cm"
---

```{r setup, include=FALSE}

### Pacages used
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("here")
library(ggplot2)
library(gridExtra)
library(dplyr)
library(tidyr)
library(weights)
library(descr)
library(knitr)
library(data.table)
library(RStata)
library(stats)
library(haven)

load(here("inst/data/cencus_dt.RData"))
load(here("inst/data/survey_dt.RData"))

#Some changes to the data


census_dt$constituency_name <-  ifelse(
                               census_dt$constituency_name %in% c(" eengodi",
                                                      " okankolo", " guinas",
                                            " tsumeb"), " nehale lyampingana",
                                              census_dt$constituency_name)

census_dt$const_code <-  ifelse(
                             census_dt$const_code %in% c("1201", "1202",
                                                 "1203","1210"), "1203",
                                                census_dt$const_code)

survey_dt$contituency_name <-  ifelse(
                                survey_dt$contituency_name %in% c(" eengodi",
                                                " okankolo", " guinas",
                                          " tsumeb"), " nehale lyampingana",
                                        survey_dt$contituency_name)


survey_dt$new_const_code <- NA
for (i in 1:nrow(survey_dt)) {
  match_row <- which(census_dt$constituency_name == survey_dt$contituency_name[i] |
                       census_dt$constituency_name == survey_dt$contituency_prev_name[i])
  if (length(match_row) > 0) {
    survey_dt$new_const_code[i] <- census_dt$const_code[match_row[1]]
  }
}

survey_dt$internet <- recode(survey_dt$internet, "Subscribed in the house"="Yes",
                                    " Accessible outside the house" ="Yes" ,
                                     "Either"="Yes",
                                    "No internet"= "No")

survey_dt$wta_hh <-as.numeric(survey_dt$wta_hh)
census_dt["wta_hh"] <- lapply(haven::zap_labels(census_dt["wta_hh"]) ,as.numeric)




#### Functions used

missing_var <- function(dt)
    {
            df <- data.frame(dt)
            missing_count <- colSums(is.na(df))
            missing_cols <- which(missing_count == nrow(df))
            names(df[, missing_cols])
            }


cand_var <- function(pop_dt, smp_dt, oth_var) {
          pop_df <- data.frame(pop_dt)
          smp_df <- data.frame(smp_dt)
          common_vars <- intersect(names(pop_df),names(smp_df))
          res <- common_vars[!(common_vars %in% oth_var)]
          fin_res <- intersect(res[!(res %in% missing_var(smp_df))],
                            res[!(res %in% missing_var(pop_df))])

          return(fin_res) 
    }




dummify <- function(x)
    {
      if(is.matrix(x) || is.data.frame(x)) {
        x <- as.data.frame(x)
        y <- do.call(data.frame, lapply(x, dummify))
        return(as.matrix(y))
      }
      # x is 1-dimensional
            if(is.complex(x))
              return(as.matrix(data.frame(Re=Re(x), Im=Im(x))))
            # convert factors etc
            if(is.character(x))
              x <- factor(x)
            if(is.logical(x))
              x <- factor(x, levels=c(FALSE,TRUE))
            if(is.factor(x)) {
              # convert to dummy variables
              nx <- length(x)
              lev <- levels(x)
              y <- matrix(0L, nrow=nx, ncol=length(lev))
              colnames(y) <- lev
              y[cbind(seq_len(nx), as.integer(x))] <- 1L
      return(y)
      }
      # convert to numeric
      y <- as.numeric(x)
      if(!is.matrix(y))
        y <- matrix(y, ncol=1)
      
      return(y)
}


compar_test_means<- function(smp_data,
                           pop_data,
                           var,
                           smp_weights,
                           pop_weights)
    {
  
              ### get the set of complete cases of the variables as
              ### would have been used in model estimation
              smp_df <- smp_data[complete.cases(c(var, smp_weights)),
                                 c(var, smp_weights)]
              pop_df <- pop_data[complete.cases(c(var, pop_weights)),
                                 c(var, pop_weights)]
              
              smp_means_df <- data.frame(smp_means = colMeans(smp_df[var]),
                                         smp_sd = apply(X = smp_df[var],
                                                        MARGIN = 2,
                                                        FUN = sd,
                                                        na.rm = TRUE),
                                         variable = var)
              
              pop_means_df <- data.frame(pop_means = colMeans(pop_df[var]),
                                         pop_sd = apply(X = pop_df[var],
                                                        MARGIN = 2,
                                                        FUN = sd,
                                                        na.rm = TRUE),
                                         variable = var)
              
              means_df <- merge(smp_means_df, pop_means_df, by = "variable")
              means_df$diff_sd <- sqrt((means_df$smp_sd)^2 + (means_df$pop_sd)^2)
              means_df$diff <- means_df$pop_means - means_df$smp_means
              means_df$zscore <- means_df$diff / means_df$diff_sd
              means_df$pvalue <- 2 * (1 - pnorm(abs(means_df$zscore)))
  
  return(means_df[, c("variable", "smp_means", "pop_means", "diff", "pvalue")])
  
    }


ebp_test_means <- function(smp_data,
                           pop_data,
                           varlist,
                           smp_weights,
                           pop_weights)
    {

  ### get the set of complete cases of the variables as
  ### would have been used in model estimation
  smp_df <- smp_data[complete.cases(c(varlist, smp_weights)),
                     c(varlist, smp_weights)]
  pop_df <- pop_data[complete.cases(c(varlist, pop_weights)),
                     c(varlist, pop_weights)]


  smp_means_df <- data.frame(smp_means = colMeans(smp_df[,varlist]),
                             smp_sd = apply(X = smp_df[,varlist],
                                            MARGIN = 2,
                                            FUN = sd,
                                            na.rm = TRUE),
                             variable = varlist)

  pop_means_df <- data.frame(pop_means = colMeans(pop_df[,varlist]),
                             pop_sd = apply(X = pop_df[,varlist],
                                            MARGIN = 2,
                                            FUN = sd,
                                            na.rm = TRUE),
                             variable = varlist)

  means_df <- merge(smp_means_df, pop_means_df, by = "variable")
  means_df$diff_sd <- sqrt((means_df$smp_sd)^2 + (means_df$pop_sd)^2)
  means_df$diff <- means_df$pop_means - means_df$smp_means
  means_df$zscore <- means_df$diff / means_df$diff_sd
  means_df$pvalue <- 2 * (1 - pnorm(abs(means_df$zscore)))
  return(means_df[, c("variable", "smp_means", "pop_means", "diff", "pvalue")])

    }



hist_plot <- function(dt, var, weights, col)
     {
         
          dt[[weights]] <- as.numeric(dt[[weights]])
          dt[[var]] <- as.numeric(dt[[var]])
          y <- as.data.frame(wtd.table(x = dt[[var]], weights = dt[[weights]]), col.names = c(var,"Proportion"))
          y[,2] <- prop.table(y[,2])
          hist <- ggplot(y, aes(x = !!sym(var), y=Proportion,fill="Census")) +
          geom_bar(stat = "identity") +
          xlab(paste("variable ", var, sep="")) +
          ylab("Proportion") +
          scale_fill_manual(values = col)+
          labs(fill="") +
          ggtitle(paste("Histogram of variable ", var, sep=""))
 
 return(hist)
  
}



countrymodel_select_stata <- function(dt,
                                      xvars,
                                      y,
                                      weights,
                                      selection = "BIC",
                                      stata_path,
                                      stata_vnum){

  dt <- as.data.table(dt)

  if(is.null(weights) == FALSE){

    dt <- na.omit(dt[,c(y, xvars, weights, "ea_id"), with = F])

    weights <- dt[, weights, with = F]

    #weights <- scale(weights)

  } else {

    dt <- na.omit(dt[,c(y, xvars, "ea_id"), with = F])

    weights <- 1

  }

  xset <- dt[, xvars, with = F]

  y <- dt[, y, with = F]

  df <- as.data.frame(dt)
  names(df) <- abbreviate(names(df), minlength = 32)

  x <- colnames(xset)

  haven::write_dta(data = df, path = "./data.dta")

  options("RStata.StataPath" = stata_path)
  options("RStata.StataVersion" = stata_vnum)

  stata_src <- c("use data.dta, replace",
                 paste0("lassowrapper ", colnames(y), " ", x[1], "-",
                        x[length(x)],", weights(hhweight) force(areadummy*) select(bic, postsel) cluster(ea_id) input(data.dta) output(model.txt)"))

  RStata::stata(src = stata_src)

  var_list <- readLines("model.txt")

  ### separate the long string by space

  var_list <- strsplit(var_list, " +")[[1]]

  var_list <- var_list[!(grepl("o.areadummy", var_list))]

  var_list <- stringr::str_replace_all(var_list, "covrfrctn", "coverfraction")
  var_list <- stringr::str_replace_all(var_list, "coverfrctn", "coverfraction")

  return(var_list)


}

```


### selection of variables to be compared between the census and the survey.
We used the `missing_var( )` and `cand_var( ) ` functions.


selection of variables to be compared between the census and the survey.

```{r }
ID <- c("hid","region_code", "region_name", "const_code","wta_hh", "wta_pop" )
cand_varlist <-cand_var(pop_dt = census_dt, smp_dt = survey_dt, oth_var=ID)
```

We have used a function called `dummify( )`  that transforms the categorical variables into dummy variables, each representing a modality of the categorical variable.


```{r}
## use of function dummify() and managing factor variable and categorical variables and producing statistics tables

cand_varlist = cand_var(pop_dt = census_dt, smp_dt = survey_dt, oth_var=ID)
dt=data.frame(dummify(census_dt[cand_varlist]))
new_varlist1=names(dt)
dt2=cbind(census_dt, dt)[c(new_varlist1, cand_varlist, "wta_hh", "const_code")]

yt=data.frame(dummify(survey_dt[cand_varlist]))
new_varlist2=names(yt)
yt2=cbind(survey_dt, yt)[c(new_varlist2, cand_varlist, "wta_hh", "new_const_code")]

varlist=intersect(new_varlist1, new_varlist2)

```



```{r}
ebp_test_means(smp_data =as.data.frame(na.omit(yt2[,c(varlist,"wta_hh")])),
                  pop_data = as.data.frame(na.omit(dt2[,c(varlist,"wta_hh")])),
                  varlist = varlist ,
                  smp_weights ="wta_hh",
                  pop_weights = "wta_hh" )
#(Table,file="Descriptive_statistics.csv", row.names = FALSE)
```



